import Head from "next/head";
import Layout from "../component/Layout";
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";

export default function Home() {

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Encode+Sans+Expanded:wght@400;700&family=Source+Sans+Pro:wght@200;300;400;600;700;900&display=swap"
          rel="stylesheet"
        ></link>
         */}
     {/* <link href='open-sans.css' rel='stylesheet' type='text/css'></link> */}
         {/* <link href="https://fonts.googleapis.com/css2?family=Encode+Sans+Expanded:wght@400;700&family=Open+Sans:ital,wght@1,300;1,400;1,500;1,600&family=Source+Sans+Pro:wght@200;300;400;600;700;900&display=swap" rel="stylesheet"></link> */}
         <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,500,600,300,700," rel="stylesheet" type="text/css"></link>
         <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" /> 
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
      </Head>
     {/* <Editor/> */}
      <Layout/>
    </div>
  );
}
