import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
// import styles from '../styles/Home.module.css'

const Title= styled.div`
font-size:50px;
`
export default function Home() {
  return (

    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
    </div>
  )
}
